name: Check
on: [push]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: javac -cp junit-4.13-rc-1.jar:hamcrest-all-1.3.jar:. *.java
      - run: java -cp junit-4.13-rc-1.jar:hamcrest-all-1.3.jar:. AllTests
